### ISSUE TITLE
No Pages Load from Example Server

### ISSUE THREAD

**Issue by michaelahlers** [outr/youi#35]
Simple setup:

```
sbt exampleJVM/run
```

Then visiting any URI (_e.g._, `http://localhost:8080/login.html`) yields errors like:

```
2017.06.03 13:56:24:862 [XNIO-1 I/O-6] ERROR i.y.E.defaultHandler:23 - java.io.FileNotFoundException: src/main/web/login.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.youi.stream.HTMLParser$$anon$1.buildCache(HTMLParser.scala:55)
	at io.youi.stream.StreamableHTML.<init>(StreamableHTML.scala:8)
	at io.youi.stream.HTMLParser$.apply(HTMLParser.scala:87)
	at io.youi.stream.HTMLParser$.$anonfun$cache$1(HTMLParser.scala:32)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:93)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:90)
	at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:320)
	at io.youi.stream.HTMLParser$.cache(HTMLParser.scala:32)
	at io.youi.app.Page.process(Page.scala:33)
	at io.youi.app.Page.process$(Page.scala:32)
	at io.youi.example.GeneralPages$.process(GeneralPages.scala:9)
	at io.youi.example.GeneralPages$.process(GeneralPages.scala:9)
	at io.youi.server.handler.HttpProcessor.$anonfun$handle$1(HttpProcessor.scala:23)
	at io.youi.server.handler.HttpProcessor.$anonfun$handle$1$adapted(HttpProcessor.scala:20)
	at scala.Option.foreach(Option.scala:257)
	at io.youi.server.handler.HttpProcessor.handle(HttpProcessor.scala:20)
	at io.youi.server.handler.HttpProcessor.handle$(HttpProcessor.scala:19)
	at io.youi.example.GeneralPages$.handle(GeneralPages.scala:9)
	at io.youi.server.Server.handleRecursive(Server.scala:89)
	at io.youi.server.Server.handle(Server.scala:66)
	at io.youi.server.Server.handle$(Server.scala:64)
	at io.youi.server.UndertowServer.handle(UndertowServer.scala:3)
	at io.youi.server.UndertowServerImplementation$$anon$2.handleRequest(UndertowServerImplementation.scala:84)
	at io.youi.server.UndertowServerImplementation.$anonfun$handleRequest$1(UndertowServerImplementation.scala:76)
	at io.youi.ErrorSupport.errorSupport(ErrorSupport.scala:9)
	at io.youi.ErrorSupport.errorSupport$(ErrorSupport.scala:8)
	at io.youi.server.UndertowServer.errorSupport(UndertowServer.scala:3)
	at io.youi.server.UndertowServerImplementation.handleRequest(UndertowServerImplementation.scala:66)
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:244)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:135)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:58)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)
```

At revision 162af13ff4ee6d1841ccfe88743cceec083a3dc1.

**Comment by darkfrog26** [comment]
try running: `;exampleJS/clean;exampleJS/fastOptJS;reStart` in `exampleJVM` or `sbt exampleJS/clean exampleJS/fastOptJS run`

**Comment by michaelahlers** [comment]
Works like a charm!
