### ISSUE TITLE
exampleJVM: No server implementation available 

### ISSUE THREAD

**Issue by maciek252** [outr/youi#55]
I want to run the example. It worked for some previous version, but after downloading a new copy I get this error after issuing sbt exampleJVM/reStart

java.lang.RuntimeException: No server implementation available.
        at io.youi.server.Server.implementation(Server.scala:44)
        at io.youi.server.Server.implementation$(Server.scala:31)
        at io.youi.example.ServerExampleApplication$.implementation$lzycompute(ServerExampleApplication.scala:8)
        at io.youi.example.ServerExampleApplication$.implementation(ServerExampleApplication.scala:8)
        at io.youi.server.Server.start(Server.scala:67)
        at io.youi.server.Server.start$(Server.scala:61)
        at io.youi.example.ServerExampleApplication$.start(ServerExampleApplication.scala:29)
        at io.youi.app.ServerApplication.main(ServerApplication.scala:283)
        at io.youi.app.ServerApplication.main$(ServerApplication.scala:281)
        at io.youi.example.ServerExampleApplication$.main(ServerExampleApplication.scala:8)
        at io.youi.example.ServerExampleApplication.main(ServerExampleApplication.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by darkfrog26** [comment]
Are you running the example from `youi/example` or `youi-example`?

**Comment by maciek252** [comment]
I have tried both.

**Comment by darkfrog26** [comment]
Nevermind, just update the project and it should be fixed. :)

**Comment by darkfrog26** [comment]
`youi` project that is

**Comment by darkfrog26** [comment]
Sorry for the delayed response, I've been traveling and just finally checked my messages.

**Comment by maciek252** [comment]
Thanks for the answer. I have cloned the youi repo from scratch. Now the server starts, but when I open http://localhost:8080/ui-examples.html, only the text "Loading..." shows.

**Comment by darkfrog26** [comment]
Yeah, the UI functionality is in a state of flux right now.  If you want to work with the UI system I would recommend checking out (or using the published dependencies) from youi 0.8.0 until 0.9.0 is released.  This is the reason that I keep doing milestone releases for 0.9.0 because I haven't had the time to finish the new functionality UI.

**Comment by maciek252** [comment]
Thanks for the answer and the excellent work! I'm learning scala.js and condider youi a perfect starting point because of its clean desing and rich UI settings. However, I would like to have the thing working and debug it - I'm able to connect the debuger from Intellij. But none of the versions I've tried works, and I can't directly apply the last fix because the file ServerApplication.scala is very different and sometimes even doesn't exist. Which version you would suggest to get the examples working?

**Comment by darkfrog26** [comment]
If you checkout the 0.8.0 tag everything should work.

**Comment by maciek252** [comment]
I clone a fresh copy, then do:
git checkout -b 0.8.0
then in sbt
exampleJS/fastOptJS
exampleJVM/reStart

and under http://localhost:8080/ui-examples.html i get only "Loading..."

the same for 0.8.2, 0.8.4 
And in fact it worked but unfortunately I don't remember for which version...

**Comment by darkfrog26** [comment]
Try this:

`git checkout tags/0.8.2 -b 0.8.2`

I just tested and it's working fine with the last 0.8.2 tag.

**Comment by maciek252** [comment]
It works! Thanks, now I can learn the framework and the scala.js capabilities :)
