### ISSUE TITLE
Cannot run example app on 0.9.0-M8

### ISSUE THREAD

**Issue by rvangsgaard** [outr/youi#56]
I am trying to use the example folder of youi to understand it. I get the error below when running

``
sbt:youi> ;exampleJS/fastOptJS;exampleJVM/run
``

and accessing in browser `http://localhost:8080/`

``
2018.04.14 13:31:13 [run-main-0] INFO io.youi.server.Server.start:68 - Server started on HTTP 192.168.2.136:8080
2018.04.14 13:31:27 [XNIO-1 I/O-3] ERROR io.youi.ErrorSupport.defaultHandler:27 - java.lang.AssertionError: assertion failed: Cannot send back /Users/rva/wc/github/youi/file:/var/folders/cj/5lyfrhc94zjfsr3b501m8qzm0000gn/T/sbt_a4bf7c5a/job-1/target/1671b480/youi-example_2.12-0.9.0-M8.jar!/content as it is a directory or does not exist!
	at scala.Predef$.assert(Predef.scala:219)
	at io.youi.http.FileContent.<init>(Content.scala:30)
	at io.youi.http.Content$.file(Content.scala:122)
	at io.youi.server.dsl.package$ClassLoaderPath.$anonfun$filter$3(package.scala:85)
	at scala.Option.map(Option.scala:146)
	at io.youi.server.dsl.package$ClassLoaderPath.filter(package.scala:84)
	at io.youi.server.dsl.CombinedConnectionFilter.filter(CombinedConnectionFilter.scala:7)
	at io.youi.server.dsl.ListConnectionFilter.$anonfun$filter$1(ListConnectionFilter.scala:7)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
	at io.youi.server.dsl.ListConnectionFilter.filter(ListConnectionFilter.scala:7)
	at io.youi.server.dsl.ConnectionFilter.handle(ConnectionFilter.scala:24)
	at io.youi.server.dsl.ConnectionFilter.handle$(ConnectionFilter.scala:24)
	at io.youi.server.dsl.ListConnectionFilter.handle(ListConnectionFilter.scala:5)
	at io.youi.server.handler.HttpHandlerBuilder$$anon$2.handle(HttpHandlerBuilder.scala:161)
	at io.youi.server.Server.handleRecursive(Server.scala:110)
	at io.youi.server.Server.handle(Server.scala:87)
	at io.youi.server.Server.handle$(Server.scala:85)
	at io.youi.example.ServerExampleApplication$.handle(ServerExampleApplication.scala:9)
	at io.youi.server.UndertowServerImplementation.$anonfun$requestHandler$1(UndertowServerImplementation.scala:104)
	at io.youi.server.UndertowServerImplementation.$anonfun$requestHandler$1$adapted(UndertowServerImplementation.scala:102)
	at io.youi.server.UndertowServerImplementation$.handle$1(UndertowServerImplementation.scala:131)
	at io.youi.server.UndertowServerImplementation$.processRequest(UndertowServerImplementation.scala:167)
	at io.youi.server.UndertowServerImplementation.requestHandler(UndertowServerImplementation.scala:102)
	at io.youi.server.UndertowServerImplementation.$anonfun$handleRequest$1(UndertowServerImplementation.scala:91)
	at io.youi.ErrorSupport.errorSupport(ErrorSupport.scala:11)
	at io.youi.ErrorSupport.errorSupport$(ErrorSupport.scala:10)
	at io.youi.example.ServerExampleApplication$.errorSupport(ServerExampleApplication.scala:9)
	at io.youi.server.UndertowServerImplementation.handleRequest(UndertowServerImplementation.scala:74)
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
``

**Comment by darkfrog26** [comment]
Try going to http://localhost:8080/dashboard.html instead

That is definitely a bug, but I want to make sure the system is still working properly apart from that.

**Comment by rvangsgaard** [comment]
Yes, it works. I will close the issue.
